import BREAKFAST_OPTIONS, {
  BREAKFAST_INGREDIENTS,
  BREAKFAST_OPTION_COLOURS,
} from '../BreakfastOptions';
import { BreakfastOption } from './BreakfastOrderContainer';

const BreakfastOptions: BreakfastOption[] = [
  {
    name: BREAKFAST_OPTIONS.FAT_BASTARD,
    ingredients: [
      BREAKFAST_INGREDIENTS.SAUSAGE,
      BREAKFAST_INGREDIENTS.BACON,
      BREAKFAST_INGREDIENTS.EGG,
    ],
    colour: BREAKFAST_OPTION_COLOURS.FAT_BASTARD,
  },
  {
    name: BREAKFAST_OPTIONS.SAUSAGE_AND_BACON,
    ingredients: [BREAKFAST_INGREDIENTS.SAUSAGE, BREAKFAST_INGREDIENTS.BACON],
    colour: BREAKFAST_OPTION_COLOURS.SAUSAGE_AND_BACON,
  },
  {
    name: BREAKFAST_OPTIONS.SAUSAGE_AND_EGG,
    ingredients: [BREAKFAST_INGREDIENTS.SAUSAGE, BREAKFAST_INGREDIENTS.EGG],
    colour: BREAKFAST_OPTION_COLOURS.SAUSAGE_AND_EGG,
  },
  {
    name: BREAKFAST_OPTIONS.EGG_AND_BACON,
    ingredients: [BREAKFAST_INGREDIENTS.BACON, BREAKFAST_INGREDIENTS.EGG],
    colour: BREAKFAST_OPTION_COLOURS.EGG_AND_BACON,
  },
  {
    name: BREAKFAST_OPTIONS.ONLY_BACON,
    ingredients: [BREAKFAST_INGREDIENTS.BACON],
    colour: BREAKFAST_OPTION_COLOURS.ONLY_BACON,
  },
  {
    name: BREAKFAST_OPTIONS.ONLY_SAUSAGE,
    ingredients: [BREAKFAST_INGREDIENTS.SAUSAGE],
    colour: BREAKFAST_OPTION_COLOURS.ONLY_SAUSAGE,
  },
  {
    name: BREAKFAST_OPTIONS.ONLY_EGG,
    ingredients: [BREAKFAST_INGREDIENTS.EGG],
    colour: BREAKFAST_OPTION_COLOURS.ONLY_EGG,
  },
];

export default BreakfastOptions;
