import BREAKFAST_OPTIONS, { BREAKFAST_OPTION_COLOURS } from '../BreakfastOptions';

const colourSwitch = (colour: string | number) => {
  switch (colour) {
    case BREAKFAST_OPTIONS.SAUSAGE_AND_BACON:
      return BREAKFAST_OPTION_COLOURS.SAUSAGE_AND_BACON;
    case BREAKFAST_OPTIONS.FAT_BASTARD:
      return BREAKFAST_OPTION_COLOURS.FAT_BASTARD;
    case BREAKFAST_OPTIONS.SAUSAGE_AND_EGG:
      return BREAKFAST_OPTION_COLOURS.SAUSAGE_AND_EGG;
    case BREAKFAST_OPTIONS.EGG_AND_BACON:
      return BREAKFAST_OPTION_COLOURS.EGG_AND_BACON;
    case BREAKFAST_OPTIONS.ONLY_BACON:
      return BREAKFAST_OPTION_COLOURS.ONLY_BACON;
    case BREAKFAST_OPTIONS.ONLY_SAUSAGE:
      return BREAKFAST_OPTION_COLOURS.ONLY_SAUSAGE;
    case BREAKFAST_OPTIONS.ONLY_EGG:
      return BREAKFAST_OPTION_COLOURS.ONLY_EGG;
    default:
      return BREAKFAST_OPTION_COLOURS.FAT_BASTARD;
  }
};

export default colourSwitch;
